"""The ecosystem-registry/v0 gate — the index that makes distributed cards discoverable.

THE SHAPE IS OWNED HERE; THE MAP IS NOT (ADR-PA-0017). Half these tests exist to hold that line:
a registry is a SUPERSET, and every field this contract does not name must survive untouched.
"""
import pytest
import yaml

from papeete_actor import registry


def reg(*rows, key="repos") -> dict:
    return {key: list(rows)}


def write(tmp_path, data) -> "object":
    path = tmp_path / "registry.yaml"
    path.write_text(data if isinstance(data, str) else yaml.safe_dump(data, sort_keys=False))
    return path


ACTOR = {"repo": "example/up", "papeete_actor": "UP.STREAM",
         "card": "papeete-actor.yaml", "card_status": "adopted"}
EXTERNAL = {"repo": "papeete-hub/kpack"}


# ── the index ─────────────────────────────────────────────────────────────────────────────────

def test_a_minimal_registry_conforms(tmp_path):
    assert registry.lint(write(tmp_path, reg(ACTOR))).errors == []


def test_an_empty_index_conforms(tmp_path):
    """A deployment whose actor set is still empty. `repos: []` is a claim; a missing key is not."""
    assert registry.lint(write(tmp_path, reg())).errors == []


def test_no_index_at_all_fails(tmp_path):
    rep = registry.lint(write(tmp_path, {"orgs": []}))
    assert any("no 'repos:'" in e for e in rep.errors)


def test_an_index_that_is_not_a_list_fails(tmp_path):
    rep = registry.lint(write(tmp_path, {"repos": {"a": 1}}))
    assert any("not a list" in e for e in rep.errors)


def test_repo_is_the_one_required_field(tmp_path):
    rep = registry.lint(write(tmp_path, reg({"papeete_actor": "UP.STREAM"})))
    assert any("missing required key 'repo'" in e for e in rep.errors)


def test_card_status_is_an_enum(tmp_path):
    rep = registry.lint(write(tmp_path, reg(dict(ACTOR, card_status="maybe"))))
    assert any("card_status='maybe'" in e for e in rep.errors)


# ── the class this gate exists for ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("status", ["adopted", "pending"])
def test_a_claimed_card_with_no_path_is_unfindable(tmp_path, status):
    """THE WORST CLASS. `check.run` skips a row with no `card:` in silence, so an adopted card is
    absent from every cross-card result with nothing reported."""
    rep = registry.lint(write(tmp_path, reg(
        {"repo": "example/up", "papeete_actor": "UP.STREAM", "card_status": status})))
    assert any("unfindable_card" in e for e in rep.errors)


def test_card_status_none_needs_no_path(tmp_path):
    """An actor that owes a card has no card to point at. That is the whole meaning of `none`."""
    assert registry.lint(write(tmp_path, reg(
        {"repo": "example/settler", "card_status": "none"}))).errors == []


def test_a_path_with_no_status_is_warned_not_failed(tmp_path):
    """It classifies EXTERNAL — "not an actor at all" — while carrying the path to its card.
    Almost always half a row rather than a claim, so it is a prompt, never a verdict."""
    rep = registry.lint(write(tmp_path, reg(
        {"repo": "example/up", "card": "papeete-actor.yaml"})))
    assert rep.errors == []
    assert any("unstated_card_status" in w for w in rep.warns)


def test_a_duplicate_repo_row_fails(tmp_path):
    rep = registry.lint(write(tmp_path, reg(ACTOR, dict(ACTOR, card_status="none"))))
    assert any("duplicate" in e for e in rep.errors)


def test_a_placeholder_row_is_noted_not_failed(tmp_path):
    """`<client>/<name>` indexes nothing and is legal — a reader just needs to know the count
    includes it."""
    rep = registry.lint(write(tmp_path, reg({"repo": "<client>/<name>"})))
    assert rep.errors == []
    assert any("placeholder" in n for n in rep.notes)


def test_two_placeholder_rows_are_not_duplicates(tmp_path):
    assert registry.lint(write(tmp_path, reg(
        {"repo": "<client>/a"}, {"repo": "<client>/b"}))).errors == []


# ── the boundary: the shape is mine, the map is not ───────────────────────────────────────────

def test_the_deployments_own_fields_never_fail_a_registry(tmp_path):
    """A registry is a SUPERSET. `orgs`, `edges`, `role`, `governed_by` model how an ecosystem
    converges; a rule about them here would be the altitude violation `hard_boundary` forbids."""
    data = {
        "orgs": [{"id": "papeete-foundry", "role": "lab"}],
        "contexts_ref": "banking-governance/gcm/vocab.yaml",
        "edges": [{"from": "a", "to": "b"}],
        "repos": [dict(ACTOR, org="example", role="lab", governed_by="ECO.GOV",
                       pinned_by=["x"], is_="engine", note="n")],
    }
    assert registry.lint(write(tmp_path, data)).errors == []


def test_unnamed_fields_are_summarised_once_not_enumerated_per_row(tmp_path):
    """65 notes against a 15-row conformant registry is the noise floor generated by the gate
    itself. The contract says `unknown_key: NOT A DEFECT`; the report has to agree with it."""
    rows = [dict(ACTOR, repo=f"example/r{i}", org="example", role="lab") for i in range(15)]
    rep = registry.lint(write(tmp_path, reg(*rows)))
    unnamed = [n for n in rep.notes if "outside ecosystem-registry/v0" in n]
    assert len(unnamed) == 1
    assert "org" in unnamed[0] and "role" in unnamed[0]


# ── classification ────────────────────────────────────────────────────────────────────────────

def test_adopted_and_pending_are_actors():
    c = registry.classes(reg(ACTOR, dict(ACTOR, repo="example/p", papeete_actor="P",
                                         card_status="pending")))
    assert c["UP.STREAM"] == "actor" and c["P"] == "actor"


def test_card_status_none_is_dangling():
    assert registry.classes(reg({"repo": "example/settler", "card_status": "none"})) \
        ["example/settler"] == "dangling"


def test_absence_of_card_status_is_external():
    """THE ABSENCE IS THE DECLARATION — the only way a registry can say "not an actor". Which is
    why `card_status` cannot be required."""
    assert registry.classes(reg(EXTERNAL))["papeete-hub/kpack"] == "external"


def test_an_actor_id_of_none_never_classifies():
    """Several rows carry it; indexing it would collide them all under one key."""
    c = registry.classes(reg(
        {"repo": "example/a", "papeete_actor": "none", "card": "c", "card_status": "adopted"},
        {"repo": "example/b", "papeete_actor": "none", "card_status": "none"}))
    assert "none" not in c
    assert c["example/a"] == "actor" and c["example/b"] == "dangling"


def test_a_row_answers_to_all_three_aliases():
    c = registry.classes(reg(ACTOR))
    assert c["example/up"] == c["up"] == c["UP.STREAM"] == "actor"


def test_the_rule_is_read_from_the_contract_not_restated(tmp_path):
    """`classification` in the schema is the single statement of it, so the gate that reports a
    misclassification and the join that acts on one cannot drift apart."""
    schema = yaml.safe_load(
        (__import__("papeete_actor.schemas", fromlist=["x"]).contracts_dir()
         / "registry.schema.yaml").read_text())
    assert schema["index"]["entry"]["enums"]["card_status"] == ["adopted", "pending", "none"]
    assert set(schema["classification"]) >= {"actor", "dangling", "external"}


def test_cards_registry_classes_still_answers_for_consumers():
    """The name papeete_actor.cards exports; the rule moved, the entry point did not."""
    from papeete_actor import cards
    assert cards.registry_classes(reg(ACTOR))["UP.STREAM"] == "actor"


# ── malformed input ───────────────────────────────────────────────────────────────────────────

def test_a_registry_that_does_not_parse_is_reported_not_raised(tmp_path):
    rep = registry.lint(write(tmp_path, "repos: [unclosed\n"))
    assert any("does not parse" in e for e in rep.errors)


def test_a_missing_registry_is_reported_not_raised(tmp_path):
    assert registry.lint(tmp_path / "nope.yaml").errors


def test_a_registry_that_is_not_a_mapping_is_reported(tmp_path):
    rep = registry.lint(write(tmp_path, ["a", "list"]))
    assert any("not a mapping" in e for e in rep.errors)


def test_a_row_that_is_not_a_mapping_is_reported(tmp_path):
    rep = registry.lint(write(tmp_path, {"repos": ["just a string"]}))
    assert any("not a mapping" in e for e in rep.errors)
