apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-inspector
  labels:
    app: car-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-inspector
  template:
    metadata:
      labels:
        app: car-inspector
    spec:
      containers:
        - name: car-inspector
          image: car-inspector
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
