"""The ecosystem-registry/v0 gate — the index that makes distributed cards discoverable.

WHAT THIS IS NOT. It does not read a single card. Everything here is decidable from the registry
alone, which is what separates it from `papeete-actor check`: "this row claims an adopted card and
gives no path to it" needs only the index, while "nobody publishes that id" needs every card at
once.

THE SHAPE IS OWNED HERE; THE MAP IS NOT (ADR-PA-0017). A registry is a superset — the reference
deployment's carries `orgs`, `edges`, `contexts_ref` and eleven per-row fields modelling how its
ecosystem converges. None of that is this contract's business, so an unnamed key is a note and
never an error. What is contracted is the index: which repos exist, and which of them carry cards.
"""
from pathlib import Path

import yaml

from .report import Report
from .schemas import load

CONTRACT = "ecosystem-registry/v0"


def classes(reg: dict, schema: dict | None = None) -> dict[str, str]:
    """Map every key the registry knows to `actor` | `dangling` | `external`.

    THE RULE IS READ FROM THE CONTRACT, not restated here. `classification` in the schema is the
    single statement of it, so the gate that reports a misclassification and the join that acts on
    one cannot drift apart — the discipline every other gate in this package already follows.
    """
    schema = schema or load("registry")
    entry = schema["index"]["entry"]
    key = schema["index"]["key"]
    statuses = set(entry["enums"]["card_status"])
    dangling = "none"
    actor_statuses = statuses - {dangling}

    out: dict[str, str] = {}
    for row in reg.get(key, []) or []:
        if not isinstance(row, dict):
            continue
        status = row.get("card_status")
        # ABSENCE IS THE DECLARATION. No `card_status` at all means "not an actor" — an engine or
        # an artifact — and is the only way a registry can say so. See `classification.external`.
        kind = ("actor" if status in actor_statuses
                else "dangling" if status == dangling
                else "external")
        for alias in (row.get("repo"), row.get("papeete_actor")):
            if alias and alias != "none":
                out[str(alias)] = kind
                if "/" in str(alias):
                    out[str(alias).split("/", 1)[-1]] = kind      # bare name, as cards write it
    return out


def lint(path: Path | str, schema: dict | None = None) -> Report:
    """Validate one registry against ecosystem-registry/v0."""
    path = Path(path)
    schema = schema or load("registry")
    rep = Report()

    try:
        reg = yaml.safe_load(path.read_text())
    except (yaml.YAMLError, OSError) as e:
        rep.errors.append(f"{path}: does not parse or cannot be read: {e}")
        return rep
    if not isinstance(reg, dict):
        rep.errors.append(f"{path}: not a mapping")
        return rep

    key = schema["index"]["key"]
    entry = schema["index"]["entry"]
    allowed = set(entry["required"]) | set(entry["optional"])
    statuses = entry["enums"]["card_status"]
    actor_statuses = [s for s in statuses if s != "none"]

    rows = reg.get(key)
    if rows is None:
        rep.errors.append(
            f"{path}: no '{key}:' — a registry with no index is not a registry. Use `{key}: []` "
            f"for a deployment whose actor set is still empty."
        )
        return rep
    if not isinstance(rows, list):
        rep.errors.append(f"{path}: '{key}' is not a list")
        return rep

    seen: dict[str, int] = {}
    # THE DEPLOYMENT'S OWN FIELDS ARE EXPECTED, SO THEY ARE COUNTED, NOT ENUMERATED. Reporting one
    # note per row per unnamed key produced 65 notes against a 15-row registry that conforms
    # perfectly — the noise floor WORK-OBSERVABILITY exists to prevent, generated by the gate
    # itself. A card's unnamed key means "fold it in, or widen the contract" because that contract
    # aims to be complete; this one says the opposite in `conformance.unknown_key`, and the report
    # has to agree with the contract it enforces.
    deployment_own: set[str] = set()
    kinds: dict[int, str] = {}
    for i, row in enumerate(rows):
        where = f"{path}: {key}[{i}]"
        if not isinstance(row, dict):
            rep.errors.append(f"{where}: not a mapping")
            continue

        repo = row.get("repo")
        where = f"{path}: {key}[{i}] '{repo or '?'}'"
        for req in entry["required"]:
            if not row.get(req):
                rep.errors.append(f"{where}: missing required key '{req}'")
        deployment_own |= set(row) - allowed

        status = row.get("card_status")
        kinds[i] = ("actor" if status in actor_statuses
                    else "dangling" if status == "none" else "external")
        if status is not None and status not in statuses:
            rep.errors.append(f"{where}: card_status='{status}' not in {statuses}")

        # THE CLASS THIS GATE EXISTS FOR. The join skips a row with no `card:` in SILENCE, so an
        # adopted card simply does not appear in the ecosystem-wide result.
        if status in actor_statuses and not row.get("card"):
            rep.errors.append(
                f"{where}: card_status '{status}' but no 'card:' path — the join cannot find it "
                f"and skips the row silently, so this card is absent from every cross-card result "
                f"with nothing reported ({CONTRACT} `conformance.unfindable_card`)"
            )
        if row.get("card") and status is None:
            rep.warns.append(
                f"{where}: declares a 'card:' path and no 'card_status' — classified EXTERNAL, "
                f"which says it is not an actor at all ({CONTRACT} `conformance.unstated_card_status`)"
            )

        if repo and "<" in str(repo):
            rep.notes.append(f"{where}: a placeholder row — indexes nothing, and counts as a row")
        elif repo:
            if str(repo) in seen:
                rep.errors.append(
                    f"{where}: duplicate of {key}[{seen[str(repo)]}] — the later row silently "
                    f"wins, so the registry holds a classification nobody chose"
                )
            seen[str(repo)] = i

    if deployment_own:
        rep.notes.append(
            f"{path}: {len(deployment_own)} field(s) outside {CONTRACT} — "
            f"{', '.join(sorted(deployment_own))}. The deployment's own model of its ecosystem; "
            f"this contract describes the index and does not constrain them."
        )

    if not rep.errors:
        counts: dict[str, int] = {}
        for kind in kinds.values():
            counts[kind] = counts.get(kind, 0) + 1
        # ROWS, not keys. One row is reachable under up to three aliases, so counting the class map
        # reports 24 actors in a registry holding 9.
        rep.oks.append(
            f"{path} conforms to {CONTRACT} ({len(rows)} row(s): "
            f"{counts.get('actor', 0)} actor, {counts.get('dangling', 0)} dangling, "
            f"{counts.get('external', 0)} external)"
        )
    return rep
